Menuitem.create(:title => 'Original Ribs', :description => 'Smothered in Chili\'s classic BBQ sauce.', :price_in_cents => 1769)
Menuitem.create(:title => 'Half Rack of Ribs', :description => 'Choose from all of our favorite flavors and your choice of one side.', :price_in_cents => 1019)
Menuitem.create(:title => 'Southern Smokehouse Burger', :description => 'With four slices of applewood smoked bacon, melted cheddar cheese, Chili\'s classic', :price_in_cents => 999)
Menuitem.create(:title => 'Big Mouth Bites', :description => 'Four mini burgers with applewood smoked bacon, American cheese, sauteed onions &...', :price_in_cents => 899)
Menuitem.create(:title => 'Spicy Seared Shrimp Tacos', :description => 'Seared spicy chile-lime shrimp wrapped in three flour tortillas and topped with...', :price_in_cents => 1079)
Menuitem.create(:title => 'Triple Dipper', :description => 'Combine your 3 favorite appetizers! Served with dipping sauces.', :price_in_cents => 1099)
Menuitem.create(:title => 'Southwestern Eggrolls', :description => 'A Crispy flour tortillas stuffed with juicy smoked chicken, black beans, corn,...', :price_in_cents => 829)
Menuitem.create(:title => 'Skillet Queso and Chips', :description => 'Cheese dip with seasoned beef. Served with warm tostada chips & fresh salsa.', :price_in_cents => 569)
Menuitem.create(:title => 'Molten Chocolate Cake', :description => 'Indulge in moist chocolate cake with a melted chocolate center topped with vanilla...', :price_in_cents => 659)